# Generated by Django 4.2.6 on 2023-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping')], default='Pending', max_length=150),
        ),
    ]
