# Generated by Django 4.2.6 on 2023-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_user_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pincode',
            field=models.TextField(default=False),
        ),
    ]
